config/routes.rb
Rails.application.routes.draw do
  resources :films
  get 'custom_lists/index'

  root 'lists#index'

  resources :lists, only: [:index, :show, :new, :create] do
    resources :bookmarks, only: [:new, :create]
    resources :movies, only: [:new, :create]  # Nested resource for creating movies under a list
  end

  resources :bookmarks, only: [:destroy]
  resources :movies, only: [:destroy]  # Route for deleting movies

  get '/books', to: 'books#index'
  get '/movies', to: 'movies#index'
  get '/bookmarks', to: 'bookmarks#index'

  # Remove the duplicate root route
  # root 'pages#home'  # Set the root path to the home page
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/book.rb
# app/models/book.rb

class Book < ApplicationRecord
  # Attributes: title, author
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :list
  belongs_to :movie
end

app/models/film.rb
class Film < ApplicationRecord
  belongs_to :list
end

app/models/list.rb
class List < ApplicationRecord
  has_many :movies

  mount_uploader :image, ImageUploader
  validates :title, presence: true, length: { maximum: 100 }
  validates :description, presence: true
end

app/models/movie.rb
class Movie < ApplicationRecord
  belongs_to :list
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookmark_controller.rb
class BookmarksController < ApplicationController
  before_action :find_list

  def new
    @bookmark = @list.bookmarks.build
  end

  def create
    @bookmark = @list.bookmarks.build(bookmark_params)
    if @bookmark.save
      redirect_to @list, notice: 'Bookmark was successfully created.'
    else
      render :new
    end
  end

  def destroy
    @bookmark = Bookmark.find(params[:id])
    @bookmark.destroy
    redirect_to @bookmark.list, notice: 'Bookmark was successfully deleted.'
  end

  private

  def find_list
    @list = List.find(params[:list_id])
  end

  def bookmark_params
    params.require(:bookmark).permit(:movie_id, :comment)
  end
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController
  def index
    @bookmarks = Bookmark.all
  end

  def new
    @list = List.find(params[:list_id])
    @bookmark = @list.bookmarks.build
  end

  def create
    @list = List.find(params[:list_id])
    @bookmark = @list.bookmarks.build(bookmark_params)
    if @bookmark.save
      redirect_to @list, notice: 'Bookmark was successfully created.'
    else
      render :new
    end
  end

  def destroy
    @bookmark = Bookmark.find(params[:id])
    @bookmark.destroy
    redirect_to @bookmark.list, notice: 'Bookmark was successfully destroyed.'
  end

  private

  def bookmark_params
    params.require(:bookmark).permit(:movie_id)
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  require_relative '../models/book'

  def index
    @books = Book.all
  end

  # Other actions...
end

app/controllers/custom_lists_controller.rb
class CustomListsController < ApplicationController
  def index
  end
end

app/controllers/films_controller.rb
class FilmsController < ApplicationController
  before_action :set_film, only: %i[ show edit update destroy ]

  # GET /films or /films.json
  def index
    @films = Film.all
  end

  # GET /films/1 or /films/1.json
  def show
  end

  # GET /films/new
  def new
    @film = Film.new
  end

  # GET /films/1/edit
  def edit
  end

  # POST /films or /films.json
  def create
    @film = Film.new(film_params)

    respond_to do |format|
      if @film.save
        format.html { redirect_to film_url(@film), notice: "Film was successfully created." }
        format.json { render :show, status: :created, location: @film }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @film.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /films/1 or /films/1.json
  def update
    respond_to do |format|
      if @film.update(film_params)
        format.html { redirect_to film_url(@film), notice: "Film was successfully updated." }
        format.json { render :show, status: :ok, location: @film }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @film.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /films/1 or /films/1.json
  def destroy
    @film.destroy

    respond_to do |format|
      format.html { redirect_to films_url, notice: "Film was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_film
      @film = Film.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def film_params
      params.require(:film).permit(:title, :release_year, :genre, :list_id)
    end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  def index
    @lists = List.all
    @movies = Movie.all
  end

  def show
    @list = List.find(params[:id])
  end

  def new
    @list = List.new
  end

  def create
    @list = List.new(list_params)
    if @list.save
      redirect_to @list, notice: 'List was successfully created.'
    else
      render :new
    end
  end

  # Other actions...

  private

  def list_params
    params.require(:list).permit(:title, :description, :image)
  end
end

# Create the directory if it doesn't exist
Dir.mkdir(Rails.root.join('app', 'views', 'lists')) unless Dir.exist?(Rails.root.join('app', 'views', 'lists'))

# Create the view templates
File.open(Rails.root.join('app', 'views', 'lists', 'index.html.erb'), 'w') do |file|
  file.puts <<~HTML
    <h1>Lists</h1>
    <% @lists.each do |list| %>
      <div>
        <h2><%= list.title %></h2>
        <p><%= list.description %></p>
        <%= link_to 'Show', list %>
      </div>
    <% end %>
  HTML
end

File.open(Rails.root.join('app', 'views', 'lists', 'show.html.erb'), 'w') do |file|
  file.puts <<~HTML
    <h1><%= @list.title %></h1>
    <p><%= @list.description %></p>
  HTML
end

File.open(Rails.root.join('app', 'views', 'lists', 'new.html.erb'), 'w') do |file|
  file.puts <<~HTML
    <h1>New List</h1>
    <%= form_for @list do |f| %>
      <div>
        <%= f.label :title %>
        <%= f.text_field :title %>
      </div>
      <div>
        <%= f.label :description %>
        <%= f.text_area :description %>
      </div>
      <div>
        <%= f.submit 'Create List' %>
      </div>
    <% end %>
  HTML
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
  def index
    @movies = Movie.all

    respond_to do |format|
      format.html # Render the default HTML template
      format.json { render json: @movies } # Render JSON response
      format.xml { render xml: @movies } # Render XML response
    end
  end

  def new
    @list = List.find(params[:list_id])
    @movie = Movie.new
  end

  def create
    @list = List.find(params[:list_id])
    @movie = @list.movies.build(movie_params)
    if @movie.save
      redirect_to @list, notice: 'Movie was successfully added.'
    else
      render :new
    end
  end

  def destroy
    @movie = Movie.find(params[:id])
    @movie.destroy
    redirect_to @movie.list, notice: 'Movie was successfully removed.'
  end

  private

  def movie_params
    params.require(:movie).permit(:title, :description)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
      # Retrieve necessary data for the home page
      @lists = List.all
      @movies = Movie.all
      @bookmarks = Bookmark.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/custom_lists_helper.rb
module CustomListsHelper
end

app/helpers/films_helper.rb
module FilmsHelper
end

app/views/bookmarks/index.html.erb
<h1>Bookmarks</h1>

<% @bookmarks.each do |bookmark| %>
  <div>
    <h2><%= bookmark.title %></h2>
    <p><%= bookmark.description %></p>
  </div>
<% end %>

app/views/bookmarks/new.html.erb
<h1>New Bookmark</h1>
<%= form_with(model: [@list, @bookmark], url: list_bookmarks_path(@list)) do |form| %>
  <%= form.label :movie_id %>
  <%=

app/views/books/index.html.erb
<!-- app/views/books/index.html.erb -->

<h1>Books</h1>

<ul>
  <% @books.each do |book| %>
    <li><%= book.title %></li>
  <% end %>
</ul>

app/views/custom_lists/index.html.erb
<h1>CustomLists#index</h1>
<p>Find me in app/views/custom_lists/index.html.erb</p>

app/views/films/_film.html.erb
<div id="<%= dom_id film %>">
  <p>
    <strong>Title:</strong>
    <%= film.title %>
  </p>

  <p>
    <strong>Release year:</strong>
    <%= film.release_year %>
  </p>

  <p>
    <strong>Genre:</strong>
    <%= film.genre %>
  </p>

  <p>
    <strong>List:</strong>
    <%= film.list_id %>
  </p>

</div>

app/views/films/_form.html.erb
<%= simple_form_for(@film) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :title %>
    <%= f.input :release_year %>
    <%= f.input :genre %>
    <%= f.association :list %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/films/edit.html.erb
<h1>Editing film</h1>

<%= render "form", film: @film %>

<br>

<div>
  <%= link_to "Show this film", @film %> |
  <%= link_to "Back to films", films_path %>
</div>

app/views/films/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Films</h1>

<div id="films">
  <% @films.each do |film| %>
    <%= render film %>
    <p>
      <%= link_to "Show this film", film %>
    </p>
  <% end %>
</div>

<%= link_to "New film", new_film_path %>

app/views/films/new.html.erb
<h1>New film</h1>

<%= render "form", film: @film %>

<br>

<div>
  <%= link_to "Back to films", films_path %>
</div>

app/views/films/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @film %>

<div>
  <%= link_to "Edit this film", edit_film_path(@film) %> |
  <%= link_to "Back to films", films_path %>

  <%= button_to "Destroy this film", @film, method: :delete %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Watch List</title>
  <!-- Include Bootstrap CSS -->
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
  <title>RailsWatchList</title>
  <meta name="viewport" content="width=device-width,initial-scale=1">
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>
  <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
</head>
<header>
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="#">Logo</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNav">
    <ul class="navbar-nav">
      <li class="nav-item">
        <a class="nav-link" href="#">Home</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#">About</a>
      </li>
      <!-- Add more navigation links as needed -->
    </ul>
  </div>
</nav>
  <%= yield %>
  <script src="path/to/your/script.js"></script> <!-- Include any JavaScript files at the end of the body -->
</header>
<body>
<img src=>
</body>
</html>

app/views/lists/form.html.erb
<%= form_with model: @list, url: lists_path, local: true, html: { multipart: true } do |form| %>
  <!-- Other form fields -->
  <%= form.file_field :image %>
  <%= form.submit 'Create List' %>
<% end %>

app/views/lists/index.html.erb
<h1>Lists</h1>
<% @lists.each do |list| %>
  <div>
    <h2><%= list.title %></h2>
    <p><%= list.description %></p>
    <%= link_to 'Show', list %>
  </div>
<% end %>

app/views/lists/new.html.erb
<h1>New List</h1>
<%= form_for @list do |f| %>
  <div>
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>
  <div>
    <%= f.label :description %>
    <%= f.text_area :description %>
  </div>
  <div>
    <%= f.submit 'Create List' %>
  </div>
<% end %>

app/views/lists/show.html.erb
<h1><%= @list.title %></h1>
<p><%= @list.description %></p>

<!-- Display movies -->
<div class="movie-container">
  <% @list.movies.each do |movie| %>
    <div class="movie-card">
      <% if movie.image.present? %>
        <%= image_tag movie.image.url, class: "movie-image" %>
      <% else %>
        <%= image_tag 'default_movie_image.jpg', class: "movie-image" %>
      <% end %>
      <h3><%= movie.title %></h3>
      <p>Release Year: <%= movie.release_year %></p>
      <p>Genre: <%= movie.genre %></p>
      <!-- Add more movie details as needed -->
    </div>
  <% end %>
</div>

app/views/movies/index.html.erb
<h1>Movies</h1>
<ul>
  <% @movies.each do |movie| %>
    <li><%= movie.title %></li>
  <% end %>
</ul>

<h1>Movies</h1>
<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Release Year</th>
      <th>Genre</th>
      <th>List</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
    <% @movies.each do |movie| %>
      <tr>
        <td><%= movie.title %></td>
        <td><%= movie.release_year %></td>
        <td><%= movie.genre %></td>
        <td><%= movie.list.title %></td>
        <td><%= link_to 'Show', movie %></td>
        <td><%= link_to 'Edit', edit_movie_path(movie) %></td>
        <td><%= link_to 'Destroy', movie, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to 'New Movie', new_movie_path %>